name: Bug 报告
description: 提交一个 bug
labels:
  - "t: bug"
  - "N"

body:
  - type: markdown
    attributes:
      value: |
        欢迎反馈 bug！在提交之前，请确保你已经搜索过已有的 issues，确保没有重复问题。
        请尽量提供多的信息，这将帮助问题更快解决。

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 详细描述你遇到的问题，可以附加截图或录屏。
      placeholder: |
        例如：
        在一条船上把大象放入冰箱之后，冰箱门就关不上了。如果把大象放到陆地上就不会有这个问题。
        - 把大象放入冰箱之前: *我是一个图片*
        - 把大象放入冰箱之后: *我是另一个图片*
        可以看到，冰箱的门被大象挡住了，所以就关不上了。
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 说明如何让这个问题再次发生，越详细越好。如果不确定如何复现，请留空。
      placeholder: |
        例如:
        1. 打开船上的冰箱门
        2. 把大象装进去
        3. 尝试关上冰箱门, 发现关不上
    validations:
      required: false

  - type: input
    id: version-ani
    attributes:
      label: Ani 版本号
      description: 你使用的 Ani 版本号，可在 "设置-界面与应用" 中找到，如 `3.0.0`。
      placeholder: "例如: 3.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 操作系统
      description: 你使用的操作系统
      multiple: true
      options:
        - Android
        - macOS (Intel)
        - macOS (M 系列芯片)
        - Windows
        - Linux
        - 其他 (请在上方描述中补充)
    validations:
      required: true

  - type: textarea
    id: logs-system
    attributes:
      label: 应用日志
      description: |
        对于 PC 端用户，在 "设置-关于" 中点击打开日志目录，把 `app.log` 复制粘贴或拖到这里。
        对于 Android 用户，目前不支持收集日志，可以跳过此步骤。
      render: 'text'
      placeholder: |
        请在这里粘贴日志内容，或拖拽文件到这里。
        请同时说明问题的发生时间，最好精确到分钟 (例如 19:43 左右)。
    validations:
      required: false
